services:

  # main bolna service
  bolna-app:
    build:
      context: ..
      dockerfile: local_setup/dockerfiles/bolna_server.Dockerfile
    image: bolna-app:latest
    ports:
      - "5001:5001"
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - ../agent_data:/app/agent_data

  # redis service used as a persistent storage
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

 # ngrok for local tunneling
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    environment:
      - NGROK_AUTHTOKEN=3AP4JV2AmehKj41lnAwbWtaBdOj_2VSkpuo2M3NQVUUnQyGot
    command:
      - "http"
      - "bolna-app:5001"
      - "--domain=ronald-statant-contrastively.ngrok-free.dev"
      - "--log=stdout"
    ports:
      - 4040:4040