version: '3'
agent:
  authtoken: 3AP4JV2AmehKj41lnAwbWtaBdOj_2VSkpuo2M3NQVUUnQyGot
tunnels:
  bolna-app:
    addr: bolna-app:5001
    proto: http
    inspect: false
    schemes:
      - https
    domain: ronald-statant-contrastively.ngrok-free.dev
